### ISSUE TITLE
mojito v0.1.0 release roadmap

### ISSUE THREAD

**Issue by colorsakura** [colorsakura/mojito#1]
## TODO

- [ ] implement loading local music library
- [ ] be able to play music
- [ ] write mojito readme
- [ ] decide what kind of public license

## Release

- [ ] add github build action workflow
